apiVersion: batch/v1
kind: Job
metadata:
  name: fail-job
spec:
  template:
    spec:
      containers:
        - name: python-container
          image: python:bullseye
          command: ["python3", "-c", "raise RuntimeError"]
      restartPolicy: Never
  backoffLimit: 3
