apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
        - name: python-container
          image: python:bullseye
          command: ["python3", "-c", "import math; print(math.pi)"]
      restartPolicy: Never
  backoffLimit: 3
